//Schema is NOT complete!
export const estateSchema = {
  title: "Estates",
  singular: "Estate",
  slug: "estates",
  emoji: "🏘️",
  singleton: false,
  metafields: [
    {
      type: "text",
      title: "videoUrl",
      key: "videoUrl",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "agencyServicePrice",
      key: "agencyServicePrice",
      value: "",
      required: false,
    },
    {
      type: "number",
      title: "commonSquare",
      key: "commonSquare",
      value: 0,
      required: false,
    },
    {
      type: "number",
      title: "livingSquare",
      key: "livingSquare",
      value: 0,
      required: false,
    },
    {
      type: "number",
      title: "kitchenSquare",
      key: "kitchenSquare",
      value: 0,
      required: false,
    },
    {
      type: "number",
      title: "ceilingHeight",
      key: "ceilingHeight",
      value: 0,
      required: false,
    },
    {
      type: "number",
      title: "allFloors",
      key: "allFloors",
      value: 0,
      required: false,
    },
    {
      type: "number",
      title: "builtYear",
      key: "builtYear",
      value: 0,
      required: false,
    },
    {
      type: "switch",
      title: "isRemodeled",
      key: "isRemodeled",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isMortgage",
      key: "isMortgage",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isRoomsFurniture",
      key: "isRoomsFurniture",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isKitchenFurniture",
      key: "isKitchenFurniture",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isElevator",
      key: "isElevator",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isServiceElevator",
      key: "isServiceElevator",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "switch",
      title: "isBargaining",
      key: "isBargaining",
      value: false,
      options: "yes,no",
      required: false,
    },
    {
      type: "text",
      title: "dealType",
      key: "dealType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "bathType",
      key: "bathType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "roomsType",
      key: "roomsType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "plateType",
      key: "plateType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "ceilingType",
      key: "ceilingType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "materialType",
      key: "materialType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "apartmentStatus",
      key: "apartmentStatus",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "parkingType",
      key: "parkingType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "transactionType",
      key: "transactionType",
      value: "",
      required: false,
    },
    {
      type: "text",
      title: "estateType",
      key: "estateType",
      value: "",
      required: false,
    },
  ],
};
