export const estateSchema = {
  title: "Estate",
  type: "estates",
  metafields: [
    {},
    {},
    {},
    {
      type: "parent",
      title: "location",
      key: "location",
      children: [
        {
          type: "text",
          title: "latitude",
          key: "latitude",
          value: "",
        },
        {
          type: "text",
          title: "longitude",
          key: "longitude",
          value: "",
        },
      ],
    },
    {
      type: "text",
      title: "videoUrl",
      key: "videourl",
      value: "",
    },
    {
      title: "address",
      key: "address",
      type: "text",
      value: "",
    },
    {
      title: "description",
      key: "description",
      type: "textarea",
      value: "",
    },
    {
      title: "price",
      key: "price",
      type: "number",
      value: null,
    },
    {
      title: "agentServicePrice",
      key: "agentserviceprice",
      type: "number",
      value: null,
    },
    {
      title: "commonSquare",
      key: "commonsquare",
      type: "number",
      value: null,
    },
    {
      title: "livingSquare",
      key: "livingsquare",
      type: "number",
      value: null,
    },
    {
      title: "kitchenSquare",
      key: "kitchensquare",
      type: "number",
      value: null,
    },
    {
      title: "ceilingHeight",
      key: "ceilingheight",
      type: "number",
      value: null,
    },
    {
      title: "floor",
      key: "floor",
      type: "number",
      value: null,
    },
    {
      title: "allFloors",
      key: "allfloors",
      type: "number",
      value: null,
    },
    {
      title: "builtYear",
      key: "builtyear",
      type: "number",
      value: null,
    },
    {
      title: "isRemodeled",
      key: "isremodeled",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isRoomsFurniture",
      key: "isroomsfurniture",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isKitchenFurniture",
      key: "iskitchenfurniture",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isElevator",
      key: "iselevator",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isServiceElevator",
      key: "isserviceelevator",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isBargaining",
      key: "isbargaining",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "isMortgage",
      key: "ismortgage",
      type: "switch",
      value: false,
      options: "yes,no",
    },
    {
      title: "rooms",
      key: "rooms",
      type: "text",
      value: "",
    },
    {
      title: "balconies",
      key: "balconies",
      type: "text",
      value: "",
    },
    {
      title: "dealType",
      key: "dealtype",
      type: "text",
      value: "",
    },
    {
      title: "bathType",
      key: "bathtype",
      type: "text",
      value: "",
    },
  ],
};
